### ISSUE TITLE
Concept 4 Question

### ISSUE THREAD

**Issue by kayaelle** [w3c-ccg/vc-ed-models#24]
Concept 4 is: 

describes a person’s participation/membership in an educational activity. Examples include: student of University of Wine Country, Apprentice Lawyer with the California bar association,

Could this also include a teacher teaching a course or a mentor mentoring a person?  Could it describe peer-to-peer education?

**Comment by anthonycamilleri** [comment]
@kayaelle in my opinion, YES to all of these. CONCEPT 4 is meant to describe **current participation/enrolment** in any activity.
