### ISSUE TITLE
Milestone 1: Agree HL Concepts

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/vc-ed-models#28]
We should agree:
- The four high level concepts to be used, and whether they cover all existing use cases
- Names for the four high level concepts
- Definitions for the four high level concepts
- Concept of specification and instantiation

Questions remaining:
- Do we use schema.org, CTDL vocabularies or choose intentionally different names to avoid confusion with these?
- How do we relate concepts?
- Do we agree with concepts of specification and instantiation

**Comment by kimdhamilton** [comment]
## Discussion from 1/25

### Enrollment

Question: does concept 4 include enrollment meaning an employee learning skills on the job?
Answer: both formally through certificates and other on-the-job (less formal). Also self-learning

Note: we may only need a reinforcement of that level of abstraction applies here.

### "specification vs instantiation"

Feedback that this was unclear.

- @ottonomy: "Understand how credential metadata applies to specific holders or many holders of related credentials"
- Phil Barker: Credential Offered vs Credential Earned

### Framing
- @ottonomy: We should keep in mind as we "choose" vocabularies, what role this group plays relative to standards bodies. We're not acting with the voice of the W3C standardization process, so probably staying open is the only choice of positioning. Identify how to use various standards such as VC Data Model to accomplish the use cases, and if there are multiple approaches that participants want to use, we can figure out how to describe that.
- @longpd: This suggests that we need to track these terms as they relate to Schema.org or CTDL, or other ‘sources’. Else those not intimately involved in the developments here (VC-edu) won’t necessarily follow these connections.

**Comment by kimdhamilton** [comment]
- does concept 4 include enrollment meaning an employee learning skills on the job?
- we may only need a reinforcement of that level of abstraction applies here.

**Comment by kimdhamilton** [comment]
"specification vs instantiation" was unclear.

@ottonomy: "Understand how credential metadata applies to specific holders or many holders of related credentials"

**Comment by kimdhamilton** [comment]
@kayaelle, myself, and Victoria Feng to submit PR

**Comment by vickstar666** [comment]
Hi Kim,

What should I prepare for this?

Sincerely,

Victoria Feng
xDemic Inc.
Founder | CEO
Email: victoria@xDemic.com
Linkedin: https://www.linkedin.com/in/fengvf/
Web: www.xdemic.com

1250 Broadway | New York | NY 10001

**Comment by kimdhamilton** [comment]
Sorry for the delay! 

This milestone is mostly about pinning down section 1.4 -- what are the high-level concepts and the other bullets listed in the [first comment above](https://github.com/w3c-ccg/vc-ed-models/issues/28#issue-793536312). 

We already have a [good start for the concepts](https://w3c-ccg.github.io/vc-ed-models/#concepts-requiring-definition-in-an-educational-context) based on previous discussions, but the discussion on 1/25 pointed to additional things we might need to clarify -- specifically, the Enrollment and "specification vs instantiation" sections are most actionable.

I think that, within 1.4, the section ["approach to definition"](https://w3c-ccg.github.io/vc-ed-models/#approach-to-definition) probably needs the most work, because that's where everyone seemed confused about the "specification vs instantiation" thing. I think the characterization that made more sense to people (rather than "specification vs instantiation") was metadata about different things, e.g.: is this metadata that applies to all holders of the credential? to a cohort of credential holders? to a single person? 

I might be butchering these examples, but roughly:
- Open Badges approaches this with properties on different types, e.g. BadgeClass vs Assertion, etc, where the Assertion-level applies to an individual recipient's receipt/attainment of the credential
- Unlike an Open Badge, Credential Engine entries don't attempt to describe information about an individual's attainment of the credential. So what we need to do is "bridge" a VC to Credential Engine entries (which is great because CE/CTDL uses JSON-LD, etc)

So a rough first attempt to describe this (because we're attempting to do this abstractly) is the following.  
- metadata about all holders of a given credential
- metadata about an individual holder of a given credential
- etc

Phil Barker mentioned we should also distinguish between offered and earned credentials (in the examples above I'm talking only about the earned ones).

Finally, it would be convenient to use a common vocabulary baseline, like either from CTDL or CEDS to anchor these concepts. In our T3 network work we were using terms like "Credential Definition" vs "Credential Award" that nicely expressed these concepts. But I can't recall where those terms were defined.

**Comment by philbarker** [comment]
A comment on the names/labels used in [section 1.4](https://w3c-ccg.github.io/vc-ed-models/#concepts-requiring-definition-in-an-educational-context):

> Concept 2 (skill): describes a learning outcome and/or skill a person ...

I think "skill" is too narrow. Competence would be better given the common definition of "knowledge skills and abilities". It's difficult to distinguish sills from abilities, so personally I prefer competence expanded as knowledge, skills and personal attributes or attitudes. By personal attributes I mean things like punctuality, resilience, integrity, empathy and so on.

> Concept 3 (diploma): ...

Again, I think diploma is too specific. In the US, "credential" is the term used -- which causes questions of scope here; elsewhere, the term "qualification" is used.  

I often find the UNESCO UNIVOC TVETipedia useful for finding definitions for terms like these, it has entries for [competence/y](https://unevoc.unesco.org/home/TVETipedia+Glossary/lang=en/filt=all/id=100), [learning outcome](https://unevoc.unesco.org/home/TVETipedia+Glossary/lang=en/filt=all/id=294) and [qualification](https://unevoc.unesco.org/home/TVETipedia+Glossary/filt=all/id=367)

**Comment by kimdhamilton** [comment]
- Kim to work with Jim on CEDS definitions
- Phil: does cross-mapping tool help?
    - https://www.lerhub.org/s/curators/m7rgf7r2tCwM3CwsQ/mapping-tool

**Comment by kimdhamilton** [comment]
- Add issuer
- Add credential subject

**Comment by kimdhamilton** [comment]
# Relevant CEDS definitions

Extracted from [CEDS Data Model Entities](https://ceds.ed.gov/dataModelEntities.aspx#Credentials)

## Credentials

Entity | Description
-- | --
Credential Definition | A resource that defines a competency or qualification, achievement, personal or organizational quality, experience, attribute, or aspect of an identity typically used to indicate suitability (See: Credential Engine’s ceterms:Credential).
Credential Offered | Information about a credential offered by a credentialing organization or other credential agent.
Credential Award | Event data that include an assertion by an agent/issuer that documents a person or organization’s qualification, achievement, personal or organizational quality, experience, attribute, or aspect of an identity as of a certain date or date range.
Credential Agent | Organization that plays one or more key roles in the lifecycle of a credential.

## Competencies

Entity | Description
-- | --
Competency Framework | A resource that includes metadata about a logically related set of Competency Definitions.
Competency Definition | A resource that includes a statement that describes a capability or behavior that a person may learn or be able to do within a given situation and environment, and may include definitions of the potential levels of mastery and metadata related to that statement.
Competency Assertion | An assertion by an agent/issuer that documents a person or organization’s qualification, achievement, personal or organizational quality, experience, attribute, or aspect of an identity as of a certain date or date range.
Competency Association | Competency Association: The relation of competency definitions to other competency definitions to support competency maps or to relate competency definitions to other objects such as learning resources.
Competency Set | An entity that supports the definition of a set of competency definitions.

## Career and Technical Education (CTE)

Entity | Description
-- | --
Program | A system of services, opportunities, or projects designed to meet academic or non-academic needs. (A Program entity may be related to an organization as the service provider and to people as program staff, participants, and recipients of program services. CEDS broadly defines Program for information about program types, such as work-study programs and athletic programs, that are not specifically defined. CEDS also has more specific program entities such as the CTE Program.)
Course | The organization of subject matter and related learning experiences provided for the instruction of students on a regular or systematic basis, usually for a predetermined period of time (e.g., a semester or a two-week workshop) to an individual or group of students (e.g., a class).
Course Section | A setting in which organized instruction of the course content is provided to one or more students for a given period of time. (A Course may be offered to more than one Course Section. Instruction may be delivered in person by one or more instructors or via a different medium. Sections that share space should be considered as separate Course Sections if they function as separate units for more than 50 percent of the time.)

## Postsecondary

Entity | Description
-- | --
PS Section | A postsecondary instructional course in a particular field of study that typically involves a prescribed number of instruction periods or meetings for enrolled students.

## K-12

Entity | Description
-- | --
K12 Course | The organization of subject matter and related learning experiences provided for the instruction of students on a regular or systematic basis, usually for a predetermined period of time (e.g., a semester or a two-week workshop) to an individual or group of students (e.g., a class).
Course Section | A setting in which organized instruction of course content is provided to one or more students for a given period of time. (A K12 Course may be offered to more than one Course Section. Instruction may be delivered in person by one or more instructors or via a different medium. Sections that share space should be considered as separate Course Sections if they function as separate units for more than 50 percent of the time.)
Program | A system of services, opportunities, or projects designed to meet academic or non-academic needs. (A Program entity may be related to an organization as the service provider, and to people as program staff, participants, or recipients of program services. CEDS broadly defines Program for information about program types, such as work-study programs or athletic programs, that are not specifically defined. CEDS also has more specific program entities, including PS Institution Program and CTE Program.)

**Comment by kimdhamilton** [comment]
^^ Note the similarities of CEDS definitions for "Course", "Course Section", and "Program" for K-12 and Career and Technical Education (CTE). 

Postsecondary, on the other hand, seems to deviate. There is a "PS Section" which seems similar in intent, but course and program are missing.

I looked at the LER Hub Mapping tool and it seems to refer to abstracted CEDS notions rather than these specific ones, or possibly those from CTE. Maybe this is what's meant by the "synthetic spine"?

**Comment by kimdhamilton** [comment]
3-week countdown started Feb 8, 2021. Comments/issues welcome. If no objections, we can close this issue on March 1, 2021.

**Comment by kayaelle** [comment]
Thinking more about concept 2: "Concept 2 (competency): describes a learning outcome and/or skill a person has as a result of participating in a learning activity. Examples of this might include piano playing, advanced woodworking, work in accordance with established sustainability practices"

I think we should make this broader to include an occupational context and recognition of achievements that may not be learner outcomes.  How about:

Concept 2 (outcome): describes a skill, ability, or achievement a person has demonstrated as a result of participating in learning or occupational activities. Examples of this might include piano playing, advanced woodworking, work in accordance with established sustainability practices, teamwork, empathy, perfect attendance, completing a marathon.

**Comment by longpd** [comment]
+1 to Kayaelle’s suggestion that this be extended to cover competencies learned through work, apprenticeship, and related occupational activities.

Cheers,
  Phil



Phillip Long, Ph.D., T3 Innovation Network, LER Pilot Projects Community Manager
e:  <mailto:phil@rhzconsulting.com>phil@rhzconsulting.com <mailto:phil@rhzconsulting.com>, 
SNS: Twitter/Telegram @RadHertz
LinkedIn: https://www.linkedin.com/in/longpd <https://www.linkedin.com/in/longpd>
—
RHz Consulting, LLC.
Inquire-Listen-Design-Prototype-Analyze-Repeat
e:phil@rhzconsulting.com <mailto:phil@rhzconsulting.com>
LinkedIn:http://www.linkedin.com/in/longpd <http://www.linkedin.com/in/longpd>
—
Senior Scholar, Georgetown University
Center for New Designs in Learning & Scholarship (CNDLS)
e: pl673@georgetown.edu <mailto:pl673@georgetown.edu>
— 
Schedule me: https://calendly.com/phil-t3/45min

**Comment by kimdhamilton** [comment]
+1 @kayaelle -- this is a good generalization

**Comment by kimdhamilton** [comment]
Extend deadline another week, to Mar 8

**Comment by kimdhamilton** [comment]
3/29: approved; ready to close
