### ISSUE TITLE
Widen scope of 'concept 2' outcome

### ISSUE THREAD

**Issue by anthonycamilleri** [w3c-ccg/vc-ed-models#33]
Thinking more about concept 2: "Concept 2 (competency): describes a learning outcome and/or skill a person has as a result of participating in a learning activity. Examples of this might include piano playing, advanced woodworking, work in accordance with established sustainability practices"

I think we should make this broader to include an occupational context and recognition of achievements that may not be learner outcomes.  How about:

Concept 2 (outcome): describes a skill, ability, or achievement a person has demonstrated as a result of participating in learning or occupational activities. Examples of this might include piano playing, advanced woodworking, work in accordance with established sustainability practices, teamwork, empathy, perfect attendance, completing a marathon.

_Originally posted by @kayaelle in https://github.com/w3c-ccg/vc-ed-models/issues/28#issuecomment-777541120_

**Comment by kimdhamilton** [comment]
Handled. Propose to close on 4/19 if no objections.
