### ISSUE TITLE
Relation of Human Beings 

### ISSUE THREAD

**Issue by anthonycamilleri** [w3c-ccg/vc-ed-models#34]
Mentioned at meeting of 22.02.21: should we include within our scope explaining the relations a credential subject has to others, e.g. as part of a team, as a member of a class etc

**Comment by anthonycamilleri** [comment]
Question: Can we cover this with our new **involvement** concept?

**Comment by longpd** [comment]
You're proposing using involvement to represent team-based activities which I think is a good notion. It leads to thinking carefully about the nature of this involvement and I expect there is a restricted set of metadata that might be worth considering, much like your suggestion of 'instance' that has a graph metadata context for clarification. 

Describing a person's contribution to a team is one of the major challenges many faculty have when trying to characterize and individuals role in a group activity.  Anything we can to do to help with this problem would be valuable. And yes, I am aware of the attending risks....

**Comment by kimdhamilton** [comment]
Propose to handle as part of involvement; close this issue on 4/19 if no objections
